### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by fabaff** [i-scream/pystatgrab#4]
pystatgrab is part of the [Fedora Package Collection](https://admin.fedoraproject.org/pkgdb/package/rpms/pystatgrab/). PR #3 is open for almost a week with no reaction from upstream. Fedora and I guess most other distributions are switching to Python 3 as default very soon.  

Can we consider that pystatgrab is dead?

**Comment by moto-timo** [comment]
The main developer is on holidays. I am out of the office at Embedded Linux Conference. Please be a little patient.

**Comment by tdb** [comment]
pystatgrab is not dead, so this issue can be closed. #3 will deal with the Python 3 fixes.
